# Generated by Django 5.0.6 on 2024-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
