# Generated by Django 5.0.6 on 2024-06-12 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authuser",
            name="jwt_token",
        ),
    ]
